# Generated by Django 6.0.5 on 2026-06-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lounge_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
    ]
