# Generated by Django 6.0.5 on 2026-06-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='description',
            new_name='desc',
        ),
    ]
