# Generated by Django 5.0.7 on 2026-06-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_remove_game_created_at_remove_game_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
    ]
