# Generated by Django 5.0.7 on 2026-06-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_remove_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='Action', max_length=100),
            preserve_default=False,
        ),
    ]
