# Generated by Django 6.0.5 on 2026-06-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
