package com.smartmeal.controller;
import com.smartmeal.dto.AuthDtos.*; import com.smartmeal.dto.MealRequest; import com.smartmeal.model.*; import com.smartmeal.repository.*; import com.smartmeal.service.*;
import jakarta.servlet.http.HttpSession; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api")
public class ApiController {
 private final AuthService auth; private final UserRepository users; private final MealRepository meals; private final RestaurantRepository restaurants; private final RecommendationService recommendations;
 public ApiController(AuthService a,UserRepository u,MealRepository m,RestaurantRepository r,RecommendationService rec){auth=a;users=u;meals=m;restaurants=r;recommendations=rec;}
 @PostMapping("/auth/register") ResponseEntity<?> register(@RequestBody RegisterRequest r,HttpSession s){try{User u=auth.register(r);s.setAttribute("userId",u.getId());return ResponseEntity.ok(publicUser(u));}catch(Exception e){return ResponseEntity.badRequest().body(Map.of("error",e.getMessage()));}}
 @PostMapping("/auth/login") ResponseEntity<?> login(@RequestBody LoginRequest r,HttpSession s){try{User u=auth.login(r);s.setAttribute("userId",u.getId());return ResponseEntity.ok(publicUser(u));}catch(Exception e){return ResponseEntity.status(401).body(Map.of("error",e.getMessage()));}}
 @PostMapping("/auth/logout") Map<String,Object> logout(HttpSession s){s.invalidate();return Map.of("ok",true);}
 @GetMapping("/profile") ResponseEntity<?> profile(HttpSession s){User u=current(s);return u==null?ResponseEntity.status(401).body(Map.of("error","Unauthorized")):ResponseEntity.ok(publicUser(u));}
 @PutMapping("/profile") ResponseEntity<?> update(@RequestBody Map<String,Object> b,HttpSession s){User u=current(s);if(u==null)return ResponseEntity.status(401).build(); if(b.get("fullName")!=null)u.setFullName(b.get("fullName").toString());if(b.get("goal")!=null)u.setGoal(b.get("goal").toString());if(b.get("dailyCalorieGoal")!=null)u.setDailyCalorieGoal(Integer.valueOf(b.get("dailyCalorieGoal").toString()));return ResponseEntity.ok(publicUser(users.save(u)));}
 @GetMapping("/meals/history") ResponseEntity<?> history(HttpSession s){User u=current(s);return u==null?ResponseEntity.status(401).build():ResponseEntity.ok(meals.findByUserOrderByEatenAtDesc(u));}
 @GetMapping("/meals/today") ResponseEntity<?> today(HttpSession s){User u=current(s);if(u==null)return ResponseEntity.status(401).build();return ResponseEntity.ok(meals.findByUserAndEatenAtBetweenOrderByEatenAtDesc(u,LocalDate.now().atStartOfDay(),LocalDate.now().plusDays(1).atStartOfDay()));}
 @PostMapping("/meals") ResponseEntity<?> add(@RequestBody MealRequest r,HttpSession s){User u=current(s);if(u==null)return ResponseEntity.status(401).build();Meal m=new Meal();m.setUser(u);m.setName(r.name());m.setMealType(r.mealType());m.setCalories(r.calories());m.setProtein(r.protein());m.setCarbs(r.carbs());m.setFat(r.fat());m.setFiber(r.fiber());return ResponseEntity.ok(meals.save(m));}
 @DeleteMapping("/meals/{id}") ResponseEntity<?> delete(@PathVariable Long id,HttpSession s){User u=current(s);Meal m=meals.findById(id).orElse(null);if(u==null||m==null||!m.getUser().getId().equals(u.getId()))return ResponseEntity.status(403).build();meals.delete(m);return ResponseEntity.noContent().build();}
 @GetMapping("/analysis/summary") ResponseEntity<?> analysis(HttpSession s){User u=current(s);return u==null?ResponseEntity.status(401).build():ResponseEntity.ok(recommendations.analysis(u));}
 @GetMapping("/recommendations") ResponseEntity<?> rec(HttpSession s){User u=current(s);return u==null?ResponseEntity.status(401).build():ResponseEntity.ok(recommendations.recommendations(u));}
 @GetMapping("/restaurants") List<Restaurant> rests(@RequestParam(defaultValue="")String q){return q.isBlank()?restaurants.findAll():restaurants.findByCuisineContainingIgnoreCaseOrTagsContainingIgnoreCase(q,q);}
 private User current(HttpSession s){Object id=s.getAttribute("userId");return id==null?null:users.findById((Long)id).orElse(null);} private Map<String,Object> publicUser(User u){Map<String,Object> m=new LinkedHashMap<>();m.put("id",u.getId());m.put("fullName",u.getFullName());m.put("email",u.getEmail());m.put("age",u.getAge());m.put("gender",u.getGender());m.put("heightCm",u.getHeightCm());m.put("weightKg",u.getWeightKg());m.put("goal",u.getGoal());m.put("dailyCalorieGoal",u.getDailyCalorieGoal());m.put("dietPreference",u.getDietPreference());return m;}
}
