# Generated by Django 6.0.5 on 2026-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_author_created_at_author_updated_at_book_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
