spring.application.name=ProjectHub
# Where are jsp files? HERE!
spring.mvc.view.prefix=/WEB-INF/views/
# Data Persistence
spring.datasource.url=jdbc:mysql://localhost:3306/<<projectdb>>?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
# For Update and Delete method hidden inputs
spring.mvc.hiddenmethod.filter.enabled=true
# Profile image upload limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


